import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Pixelify_Sans,
  Inter,
  Jersey_10,
} from "next/font/google";
import "./globals.css";
import ThemeProviders from "@/providers/providers";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Codex Box",
  description: "Generated by create next app",
};

const GameFont = Jersey_10({
  subsets: ["latin"],
  variable: "--font-game",
  weight: ["400"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider signUpUrl="/sign-up" signInUrl="/sign-in">
      <html lang="en" suppressHydrationWarning className="dark">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${GameFont.variable} ${inter.variable} antialiased `}
        >
          <ThemeProviders attribute="class" defaultTheme="dark">
            <div className="flex flex-col items-center font-game">
              <Header />
            </div>
            {children}
          </ThemeProviders>
        </body>
      </html>
    </ClerkProvider>
  );
}
